#!/bin/bash 
#bdereims@gmail.com | cloud-garage project
#create and configute vcn

. ./env

COMP_ID=$( oci iam compartment list --compartment-id-in-subtree true --all | jq -r '.["data"] | .[] | select(."name" == "'${COMP_NAME}'") | .id' )
VCN_ID=$( oci network vcn list -c ${COMP_ID} | jq -r '.["data"] | .[] | select(."display-name" == "'${VCN_NAME}'") | .id' ) 

# security group
NSG_ID=$( oci network nsg create -c ${COMP_ID} --vcn-id ${VCN_ID} --display-name "${VCN_NAME}" | jq -r '.["data"] | .id' )
oci network nsg rules add --nsg-id ${NSG_ID} --security-rules '[{"description":"wireguard","destination":null,"destination-type":null,"direction":"INGRESS","icmp-options":null,"is-stateless":false,"protocol":"17","source":"0.0.0.0/0","source-type":"CIDR_BLOCK","tcp-options":null,"udp-options":{"destination-port-range":{"max":8172,"min":8172},"source-port-range":null}},{"description":"internal flows","destination":null,"destination-type":null,"direction":"INGRESS","icmp-options":null,"is-stateless":false,"protocol":"all","source":"10.0.0.0/16","source-type":"CIDR_BLOCK","tcp-options":null,"udp-options":null}]'
